/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os produtos */
        get: operations["ProductController_findAll"];
        put?: never;
        /** Criar um novo produto */
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/with-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os produtos com seus custos */
        get: operations["ProductController_findAllWithCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar produto por ID */
        get: operations["ProductController_findOne"];
        put?: never;
        post?: never;
        /** Remover produto */
        delete: operations["ProductController_remove"];
        options?: never;
        head?: never;
        /** Atualizar produto */
        patch: operations["ProductController_update"];
        trace?: never;
    };
    "/product/cost/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os custos de produto */
        get: operations["ProductController_findAllCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar um custo de produto */
        post: operations["ProductController_createCost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/cost/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar custo de produto */
        patch: operations["ProductController_updateCost"];
        trace?: never;
    };
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os pedidos */
        get: operations["OrderController_findAll"];
        put?: never;
        /** Criar um novo pedido */
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/with-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os pedidos com itens */
        get: operations["OrderController_findAllWithItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar pedido por ID */
        get: operations["OrderController_findOne"];
        put?: never;
        post?: never;
        /** Remover pedido */
        delete: operations["OrderController_remove"];
        options?: never;
        head?: never;
        /** Atualizar pedido */
        patch: operations["OrderController_update"];
        trace?: never;
    };
    "/order/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar pedido com itens por ID */
        get: operations["OrderController_findOneWithItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os clientes */
        get: operations["ClientController_findAll"];
        put?: never;
        /** Criar um novo cliente */
        post: operations["ClientController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar cliente por ID */
        get: operations["ClientController_findOne"];
        put?: never;
        post?: never;
        /** Remover cliente */
        delete: operations["ClientController_remove"];
        options?: never;
        head?: never;
        /** Atualizar cliente */
        patch: operations["ClientController_update"];
        trace?: never;
    };
    "/webhooks/external-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recebe webhook de pedidos de plataforma externa
         * @description Endpoint para processar webhooks de pedidos de sistemas externos
         */
        post: operations["WebhookController_handleExternalOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter dados consolidados da dashboard
         * @description Retorna métricas consolidadas (pedidos, faturamento, custo, lucro) e série temporal de pedidos para gráfico
         */
        get: operations["DashboardController_getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProductDto: {
            /**
             * @description External ID
             * @example EXT-001
             */
            externalId: string;
            /**
             * @description Nome do produto
             * @example Notebook Dell
             */
            name: string;
            /**
             * @description Product Cost ID
             * @example COST-001
             */
            productCostId?: string;
        };
        ProductResponseDto: {
            /**
             * @description Product Cost ID
             * @example COST-001
             */
            productCostId: Record<string, never> | null;
            /** @description ID do produto */
            id: string;
            /** @description External ID */
            externalId: string;
            /** @description Nome do produto */
            name: string;
            /** @description Product ID */
            productId: string;
            /**
             * Format: date-time
             * @description Data de criação
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data de atualização
             */
            updatedAt: string;
        };
        ProductCostResponseDto: {
            /** @description ID do custo */
            id: string;
            /** @description Custo do produto */
            cost: number;
            /**
             * Format: date-time
             * @description Data de criação
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data de atualização
             */
            updatedAt: string;
        };
        ProductWithCostResponseDto: {
            /** @description ID do produto */
            id: string;
            /** @description External ID */
            externalId: string;
            /** @description Nome do produto */
            name: string;
            /** @description Product Cost ID */
            productCostId: Record<string, never> | null;
            /** @description Custo associado ao produto */
            cost?: components["schemas"]["ProductCostResponseDto"] | null;
            /**
             * Format: date-time
             * @description Data de criação
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data de atualização
             */
            updatedAt: string;
        };
        UpdateProductDto: {
            /**
             * @description External ID
             * @example EXT-001
             */
            externalId?: string;
            /**
             * @description Nome do produto
             * @example Notebook Dell
             */
            name?: string;
            /**
             * @description Product Cost ID
             * @example COST-001
             */
            productCostId?: string;
        };
        CreateProductCostDto: {
            /**
             * @description Custo do produto
             * @example 1500
             */
            cost: number;
        };
        CreateOrderDto: {
            /**
             * @description External ID
             * @example EXT-ORDER-001
             */
            externalId: string;
            /**
             * @description ID do cliente
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientId: string;
        };
        OrderItemResponseDto: {
            /** @description ID do produto */
            productId: string;
            /** @description External ID */
            externalId: string;
            /** @description ID do pedido */
            orderId: string;
            /** @description Preço */
            price: number;
        };
        OrderResponseDto: {
            /** @description ID do pedido */
            id: string;
            /** @description External ID */
            externalId: string;
            /** @description ID do cliente */
            clientId: string;
            /** @description Itens do pedido */
            items?: components["schemas"]["OrderItemResponseDto"][];
            /**
             * Format: date-time
             * @description Data de criação
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data de atualização
             */
            updatedAt: string;
        };
        UpdateOrderDto: {
            /**
             * @description External ID
             * @example EXT-ORDER-001
             */
            externalId?: string;
            /**
             * @description ID do cliente
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientId?: string;
        };
        CreateClientDto: {
            /**
             * @description Nome do cliente
             * @example João Silva
             */
            name: string;
            /**
             * @description Email do cliente
             * @example joao@email.com
             */
            email: string;
        };
        ClientResponseDto: {
            /** @description ID do cliente */
            id: string;
            /** @description Nome do cliente */
            name: string;
            /** @description Email do cliente */
            email: string;
            /**
             * Format: date-time
             * @description Data de criação
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data de atualização
             */
            updatedAt: string;
        };
        UpdateClientDto: {
            /**
             * @description Nome do cliente
             * @example João Silva
             */
            name?: string;
            /**
             * @description Email do cliente
             * @example joao@email.com
             */
            email?: string;
        };
        BuyerDto: {
            /**
             * @description Nome do comprador
             * @example Maria Souza
             */
            buyerName: string;
            /**
             * @description Email do comprador
             * @example maria@email.com
             */
            buyerEmail: string;
        };
        LineItemDto: {
            /**
             * @description ID do item
             * @example P-001
             */
            itemId: string;
            /**
             * @description Nome do item
             * @example Camiseta Básica
             */
            itemName: string;
            /**
             * @description Quantidade
             * @example 2
             */
            qty: number;
            /**
             * @description Preço unitário
             * @example 49.9
             */
            unitPrice: number;
        };
        CreateWebhookDto: {
            /**
             * @description ID do pedido externo
             * @example ORD-98432
             */
            id: string;
            /** @description Dados do comprador */
            buyer: components["schemas"]["BuyerDto"];
            /** @description Itens do pedido */
            lineItems: components["schemas"]["LineItemDto"][];
            /**
             * @description Valor total
             * @example 229.7
             */
            totalAmount: number;
            /**
             * @description Data de criação
             * @example 2025-02-10T14:32:00Z
             */
            createdAt: string;
        };
        OrderTimeSeriesDto: {
            /**
             * @description Data
             * @example 2025-01-15
             */
            date: string;
            /**
             * @description Quantidade de pedidos
             * @example 5
             */
            count: number;
        };
        DashboardResponseDto: {
            /**
             * @description Quantidade total de pedidos
             * @example 150
             */
            totalOrders: number;
            /**
             * @description Faturamento total
             * @example 45000
             */
            totalRevenue: number;
            /**
             * @description Custo total de produtos vendidos
             * @example 30000
             */
            totalCost: number;
            /**
             * @description Lucro (faturamento - custo)
             * @example 15000
             */
            profit: number;
            /** @description Série temporal de pedidos para gráfico */
            orderTimeSeries: components["schemas"]["OrderTimeSeriesDto"][];
            /**
             * @description Período de análise
             * @example {
             *       "startDate": "2025-01-01",
             *       "endDate": "2025-12-31"
             *     }
             */
            period: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de produtos retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseDto"][];
                };
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Produto criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_findAllWithCost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de produtos com custos retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductWithCostResponseDto"][];
                };
            };
        };
    };
    ProductController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do produto */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseDto"];
                };
            };
            /** @description Produto não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do produto */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto removido com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do produto */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Produto atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_findAllCosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de custos retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCostResponseDto"][];
                };
            };
        };
    };
    ProductController_createCost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductCostDto"];
            };
        };
        responses: {
            /** @description Custo criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCostResponseDto"];
                };
            };
        };
    };
    ProductController_updateCost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do custo */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductCostDto"];
            };
        };
        responses: {
            /** @description Custo atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCostResponseDto"];
                };
            };
            /** @description Custo não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de pedidos retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"][];
                };
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description Pedido criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findAllWithItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de pedidos com itens retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"][];
                };
            };
        };
    };
    OrderController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do pedido */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Pedido não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do pedido */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido removido com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pedido não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do pedido */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDto"];
            };
        };
        responses: {
            /** @description Pedido atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pedido não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findOneWithItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do pedido */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido com itens encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description Pedido não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de clientes retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"][];
                };
            };
        };
    };
    ClientController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientDto"];
            };
        };
        responses: {
            /** @description Cliente criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do cliente */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do cliente */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente removido com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do cliente */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientDto"];
            };
        };
        responses: {
            /** @description Cliente atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhookController_handleExternalOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookDto"];
            };
        };
        responses: {
            /** @description Webhook processado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        message?: string;
                    };
                };
            };
            /** @description Erro ao processar webhook - dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro interno ao processar webhook */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getDashboard: {
        parameters: {
            query?: {
                /** @description Data de início (formato ISO) */
                startDate?: string;
                /** @description Data de fim (formato ISO) */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados da dashboard retornados com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
            /** @description Parâmetros de consulta inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
